apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: fortiweb-terraform-deploy
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  ui:
    input:
      variables:
        project_id:
          name: project_id
          title: Project Id
          invisible: true
        goog_cm_deployment_name:
          name: goog_cm_deployment_name
          title: Goog Cm Deployment Name
        source_image:
          name: source_image
          title: Image Version
          section: fortiweb
          enumValueLabels:
            - label: 7.2.10
              value: projects/fortigcp-project-001/global/images/fwb-7210-payg-08132024-001-w-license
            - label: 7.4.5
              value: projects/fortigcp-project-001/global/images/fwb-745-payg-09162024-001-w-license
            - label: 7.6.3
              value: projects/fortigcp-project-001/global/images/fwb-763-payg-03102025-001-w-license
          xGoogleProperty:
            type: ET_GCE_DISK_IMAGE
        zone:
          name: zone
          title: Zone
          section: fortiweb
          xGoogleProperty:
            type: ET_GCE_ZONE
        machine_type:
          name: machine_type
          title: Machine type
          section: instance
          xGoogleProperty:
            type: ET_GCE_MACHINE_TYPE
            zoneProperty: zone
            gceMachineType:
              diskImageProperty: source_image
        boot_disk_size:
          name: boot_disk_size
          title: Boot disk size in GB
          tooltip: Persistent disk performance is tied to the size of the persistent disk volume. You are charged for the actual amount of provisioned disk space.
          min: 31
          max: 10000
          section: boot_disk
          xGoogleProperty:
            type: ET_GCE_DISK_SIZE
            gceDiskSize:
              diskTypeVariable: boot_disk_type
        boot_disk_type:
          name: boot_disk_type
          title: Boot disk type
          section: boot_disk
          xGoogleProperty:
            type: ET_GCE_DISK_TYPE
            zoneProperty: zone
        enable_tcp_22:
          name: enable_tcp_22
          title: Allow TCP port 22 traffic
          section: networking
          xGoogleProperty:
            type: ET_GCE_FIREWALL
            gceFirewall:
              networkVariable: networks
        enable_tcp_80:
          name: enable_tcp_80
          title: Allow HTTP traffic
          section: networking
          xGoogleProperty:
            type: ET_GCE_FIREWALL
            gceFirewall:
              networkVariable: networks
        enable_tcp_443:
          name: enable_tcp_443
          title: Allow HTTPS traffic
          section: networking
          xGoogleProperty:
            type: ET_GCE_FIREWALL
            gceFirewall:
              networkVariable: networks
        enable_tcp_8080:
          name: enable_tcp_8080
          title: Allow TCP port 8080 traffic
          section: networking
          xGoogleProperty:
            type: ET_GCE_FIREWALL
            gceFirewall:
              networkVariable: networks
        enable_tcp_8443:
          name: enable_tcp_8443
          title: Allow TCP port 8443 traffic
          section: networking
          xGoogleProperty:
            type: ET_GCE_FIREWALL
            gceFirewall:
              networkVariable: networks
        external_ips:
          name: external_ips
          title: External IP
          tooltip: 'An external IP address associated with this instance. Selecting "None" will result in the instance having no external internet access. <a href="https://cloud.google.com/compute/docs/configure-instance-ip-addresses">Learn more</a>'
          minItems: 1
          maxItems: 8
          section: networking
          xGoogleProperty:
            type: ET_GCE_EXTERNAL_IP
            gceExternalIp:
              networkVariable: networks
              notConfigurable: false
              allowStaticIps: true
        networks:
          name: networks
          title: Network name
          minItems: 1
          maxItems: 8
          section: networking
          xGoogleProperty:
            type: ET_GCE_NETWORK
            gceNetwork:
              allowSharedVpcs: true
              machineTypeVariable: machine_type
        sub_networks:
          name: sub_networks
          title: Subnetwork name
          minItems: 1
          maxItems: 8
          section: networking
          xGoogleProperty:
            type: ET_GCE_SUBNETWORK
            zoneProperty: zone
            gceSubnetwork:
              networkVariable: networks
        tcp_22_ip_source_ranges:
          name: tcp_22_ip_source_ranges
          title: Source IP ranges for SSH traffic
          tooltip: Traffic is only allowed from sources within these IP address ranges. Use CIDR notation when entering ranges. <a href="https://cloud.google.com/compute/docs/networking#firewalls">Learn more</a>
          placeholder: 0.0.0.0/0, 192.169.0.2/24
          section: networking
          xGoogleProperty:
            type: ET_GCE_FIREWALL_RANGE
            gceFirewallRange:
              firewallVariable: enable_tcp_22
        tcp_80_ip_source_ranges:
          name: tcp_80_ip_source_ranges
          title: Source IP ranges for HTTP traffic
          tooltip: Traffic is only allowed from sources within these IP address ranges. Use CIDR notation when entering ranges. <a href="https://cloud.google.com/compute/docs/networking#firewalls">Learn more</a>
          placeholder: 0.0.0.0/0, 192.169.0.2/24
          section: networking
          xGoogleProperty:
            type: ET_GCE_FIREWALL_RANGE
            gceFirewallRange:
              firewallVariable: enable_tcp_80
        tcp_443_ip_source_ranges:
          name: tcp_443_ip_source_ranges
          title: Source IP ranges for HTTPS traffic
          tooltip: Traffic is only allowed from sources within these IP address ranges. Use CIDR notation when entering ranges. <a href="https://cloud.google.com/compute/docs/networking#firewalls">Learn more</a>
          placeholder: 0.0.0.0/0, 192.169.0.2/24
          section: networking
          xGoogleProperty:
            type: ET_GCE_FIREWALL_RANGE
            gceFirewallRange:
              firewallVariable: enable_tcp_443
        tcp_8080_ip_source_ranges:
          name: tcp_8080_ip_source_ranges
          title: Source IP ranges for TCP 8080 traffic
          tooltip: Traffic is only allowed from sources within these IP address ranges. Use CIDR notation when entering ranges. <a href="https://cloud.google.com/compute/docs/networking#firewalls">Learn more</a>
          placeholder: 0.0.0.0/0, 192.169.0.2/24
          section: networking
          xGoogleProperty:
            type: ET_GCE_FIREWALL_RANGE
            gceFirewallRange:
              firewallVariable: enable_tcp_8080
        tcp_8443_ip_source_ranges:
          name: tcp_8443_ip_source_ranges
          title: Source IP ranges for TCP8443 traffic
          tooltip: Traffic is only allowed from sources within these IP address ranges. Use CIDR notation when entering ranges. <a href="https://cloud.google.com/compute/docs/networking#firewalls">Learn more</a>
          placeholder: 0.0.0.0/0, 192.169.0.2/24
          section: networking
          xGoogleProperty:
            type: ET_GCE_FIREWALL_RANGE
            gceFirewallRange:
              firewallVariable: enable_tcp_8443
        enable_ip_forward:
          name: enable_ip_forward
          title: Enable IP Forward
          tooltip: Forwarding allows the instance to help route packets. <a href="https://cloud.google.com/compute/docs/networking#canipforward">Learn more</a>
          section: networking
        enable_meta_user:          
          name: enable_meta_user
          title: Enable initial bootup using user data
          section: metadata
        user_data_value:
          name: user_data_value
          title: The path of config file run at bootstrap
          tooltip: Enter the path of config file run at bootstrap
          section: metadata        
      sections:
      - name: fortiweb
        title: FortiWeb (PAYG)
        subtext: Image Version
      - name: instance
        title: Instance
      - name: boot_disk
        title: Boot Disk
        tooltip: Each instance requires a disk to boot from.
      - name: networking
        title: Networking
      - name: metadata
        title: MetaData

